name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: left
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg

          # Options
          user: GZTimeWalker
          template: classic
          base: header, activity, community
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 500
          plugin_languages_threshold: 0%
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: no
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_padding: 0, 8 + 11%
          config_order: base.header, base.activity+community, languages, habits

      - name: right
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.right.svg

          # Options
          user: GZTimeWalker
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_rss: yes
          plugin_rss_source: https://blog.gztime.cc/atom.xml
          plugin_rss_limit: 4
          config_padding: 0, 8 + 11%
          config_order: achievements, rss
