name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: left
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: 7b91e5c1e018c9e35d38669d2fbd6e97

          # Options
          user: GZTimeWalker
          template: classic
          base: header, activity, community
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_ignored: html, css
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_aliases: 'Jupyter Notebook:Ipynb'
          commits_authoring: GZTimeWalker, Time.GZ@outlook.com, gztimewalker@163.com, du_du_waw@163.com, gz.time.walker@gmail.com, GZTimeHacker
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_padding: 0, 8 + 11%
          config_order: base.header, base.activity+community, languages, habits

      - name: right
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: b688af797a7cf82ab466dacd7bc10d0d

          # Options
          user: GZTimeWalker
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_limit: 6
          plugin_rss: yes
          plugin_rss_source: https://blog.gztime.cc/atom.xml
          plugin_rss_limit: 4
          config_padding: 0, 8 + 11%
          config_order: achievements, rss
