name: Metrics

on:
  # Schedule updates (every 5:00 am)
  schedule: [{cron: "0 5 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  generate_profile:
    runs-on: ubuntu-latest
    steps:
      - name: left
        uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: 7b91e5c1e018c9e35d38669d2fbd6e97

          # Options
          user: GZTimeWalker
          template: classic
          base: header, activity, community
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_ignored: 'html, css, Jupyter Notebook'
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_aliases: 'RenderScript:Rust'
          commits_authoring: GZTimeWalker, Time.GZ@outlook.com, gztimewalker@163.com, du_du_waw@163.com, gz.time.walker@gmail.com, GZTimeHacker
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_rss: yes
          plugin_rss_source: https://blog.gzti.me/atom.xml
          plugin_rss_limit: 4
          config_padding: 0, 8 + 11%
          config_order: base.header, base.activity+community, languages, habits, rss
          
      - name: right
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: b688af797a7cf82ab466dacd7bc10d0d

          # Options
          user: GZTimeWalker
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_limit: 8
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          config_padding: 0, 8 + 11%
          config_order: achievements, wakatime
  
      - name: snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg?palette=github-light
            github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      - name: deploy snake to gist
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          gist_id: 62c190858bed9a108ce5811f715d2e55
          gist_file_name: github-snake.svg
          file_path: github-snake.svg

      - name: deploy dark snake to gist
        uses: exuanbo/actions-deploy-gist@v1.1.4
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          gist_id: 62c190858bed9a108ce5811f715d2e55
          gist_file_name: github-snake-dark.svg
          file_path: github-snake-dark.svg
